"""
File Summary:
Parses pipe-separated "key: value" template strings back into row dicts.
Works on text generated by the heuristic template in Schema Analyzer.
Also handles JSON documents stored by the v3.0 forward pipeline upgrade.

====================================================================
Startup
====================================================================

heuristic_parser
||
├── parse()  [Function] ----------------------------------> Parse one document string into {col: value} dict
│       │
│       ├── [Early Exit Branch] doc_string is None ------> Return None
│       │
│       ├── [Conditional Branch] doc starts with "{" ----> Path A: JSON document
│       │       │
│       │       ├── json.loads() ------------------------> Parse JSON dict
│       │       ├── _coerce_row()  [Function] -----------> Align and coerce types
│       │       │
│       │       └── [Exception Block] JSONDecodeError ---> Fall through to regex path
│       │
│       ├── Path B: pipe-separated heuristic template ---> Apply _KV_PATTERN regex
│       │       │
│       │       ├── [Early Exit Branch] no matches ------> Log warning, return None
│       │       │
│       │       └── _coerce_row()  [Function] -----------> Align and coerce types
│       │
│       └── Returns {col: typed_value} dict or None
│
├── _coerce_row()  [Function] ----------------------------> Align raw dict to strategy.all_cols
│       │
│       ├── Loop strategy.all_cols ----------------------> Only keep known columns
│       │
│       ├── [Conditional Branch] col in numeric_cols ----> _coerce_numeric()
│       │
│       └── Else: strip residual quote chars ------------> Clean string values
│
├── _coerce_numeric()  [Function] -----------------------> Coerce value to int, float, or None
│       │
│       ├── Handle null / none / empty string -----------> Return None
│       ├── Handle true / yes / false / no --------------> Return 1 or 0
│       ├── Try int() conversion ------------------------> Return int if possible
│       └── Try float() conversion ----------------------> Return float or None
│
└── parse_batch()  [Function] ---------------------------> Parse list of documents, return same-length list

====================================================================
FUNCTION / CLASS ENTRY POINT MARKERS
====================================================================
"""

from __future__ import annotations

import json
import logging
import re
from typing import Optional

logger = logging.getLogger(__name__)

# ── Pattern matches "column_name: value" pairs separated by " | "
# Group 1: key (word chars, spaces, dots, dashes)
# Group 2: value (anything up to the next " | " or end of string)
_KV_PATTERN = re.compile(
    r"([\w][\w\s\.\-]*):\s*(.*?)(?=\s*\|\s*[\w][\w\s\.\-]*:|$)",
    re.DOTALL,
)


"""================= Startup function parse ================="""
def parse(doc_string: Optional[str], strategy, meta: Optional[dict] = None, chromadb_id: Optional[str] = None) -> Optional[dict]:
    """
    Parse one document string from Vector DB into a {col: typed_value} dict.

    Returns None if:
      - doc_string is None (document was not stored during ingestion)
      - parsing yields zero recognised columns

    strategy: SchemaStrategy from schema_loader.load()
    meta: Optional metadata dict from ChromaDB (contains rowid, source, table_or_sheet)
    chromadb_id: Optional ChromaDB ID (often the original row ID)
    """
    if doc_string is None:
        return None

    doc = doc_string.strip()
    if not doc:
        return None

    # ── Path A: JSON document (v3.0 forward upgrade) ─────────────────────────
    if doc.startswith("{"):
        try:
            raw = json.loads(doc)
            if isinstance(raw, dict):
                return _coerce_row(raw, strategy, meta, chromadb_id)
        except json.JSONDecodeError:
            pass  # fall through to regex path

    # ── Path B: pipe-separated heuristic template ─────────────────────────────
    matches = _KV_PATTERN.findall(doc)
    if not matches:
        logger.warning("[HeuristicParser] no kv pairs found in doc: %.80s", doc)
        return None

    raw = {k.strip(): v.strip() for k, v in matches}
    return _coerce_row(raw, strategy, meta, chromadb_id)
"""================= End function parse ================="""


"""================= Startup function _coerce_row ================="""
def _coerce_row(raw: dict, strategy, meta: Optional[dict] = None, chromadb_id: Optional[str] = None) -> dict:
    """
    Align raw parsed dict to strategy.all_cols and coerce types.
    Columns not found in raw are set to None.
    Extra keys not in all_cols are silently dropped.
    
    Attempts to recover missing columns from metadata and ChromaDB ID:
    - If rowid_col (e.g., 'id') is missing, use chromadb_id
    - If other id_cols are missing, check metadata
    """
    row: dict = {}

    for col in strategy.all_cols:
        val = raw.get(col)

        # Try to recover missing columns from metadata or ChromaDB ID
        if val is None or (isinstance(val, str) and val == ""):
            # If this is the rowid column and we have a ChromaDB ID, use it
            if col == strategy.rowid_col and chromadb_id is not None:
                try:
                    # Try to convert to int if it looks like a number
                    if chromadb_id.isdigit():
                        row[col] = int(chromadb_id)
                    else:
                        row[col] = chromadb_id
                    continue
                except (ValueError, AttributeError):
                    pass
            
            # Check if metadata has this column
            if meta and col in meta:
                row[col] = meta[col]
                continue
            
            row[col] = None
            continue

        if col in strategy.numeric_cols:
            row[col] = _coerce_numeric(val)
        else:
            # Clean up any residual quote chars that may have leaked from template
            row[col] = str(val).strip().strip('"').strip("'")

    return row
"""================= End function _coerce_row ================="""


"""================= Startup function _coerce_numeric ================="""
def _coerce_numeric(val) -> int | float | None:
    """
    Try to coerce a value to int, then float, then None.
    Handles common representations: '1', '3.14', 'true'/'false', 'null'/'none'.
    """
    if val is None:
        return None

    s = str(val).strip().lower()

    if s in ("null", "none", ""):
        return None
    if s in ("true", "yes"):
        return 1
    if s in ("false", "no"):
        return 0

    try:
        i = int(s)
        return i
    except (ValueError, TypeError):
        pass

    try:
        return float(s)
    except (ValueError, TypeError):
        return None
"""================= End function _coerce_numeric ================="""


"""================= Startup function parse_batch ================="""
def parse_batch(doc_strings, strategy):
    """Parse a list of document strings; returns list of same length."""
    return [parse(doc, strategy) for doc in doc_strings]
"""================= End function parse_batch ================="""